### ISSUE TITLE
branches management

### ISSUE THREAD

**Issue by marsz** [5fpro/rails4-template#16]
目前的 branch 有 `master`, `with-assets`
## master
- 算是 base branch，所有的 branch 都會從這裡開出來
- 很基礎，沒有預設任何目的性，只放其他 branch 都會共用的東西，例如 sidekiq、mailer
## with-assets
- 就是有前端的，包含後台
## 需求一

想要開一個純 API 目的的 branch，裡面會有 error 的統一格式處理，同時也包含 user sign 後的 token 處理
## 需求二

可能會有混合型的需求，例如同時有前端、也有 API 都在同一個 app 內
## 問題
- 開太多 branch 的話，master 萬一有大更新，其他的 branch 都要 rebase，像這次 rails 4.1 -> 4.2， with-assets 就 rebase 了好久
- 承上，也有重複性問題，例如 A, B, C branch 都是從 master 長出來，假如有一個地方只有 B, C 共用，但 A 用不到，這樣改 master 也不對，就只能重複去改 B, C
## 解決方案
- 維持目前兩個 branch 就好，master 就直接進化為需求一，然後 with-assets 就會自動進化成需求二 XD

@phrase5036  @kzdahlia  @ohmkao  有沒有其他的想法?

**Comment by phrase5036** [comment]
表示贊成, 目前遇到差異最大的就是這兩種branch了, 開太多branch C的功能又要拿去A也很魯小
如果有些東西是 option 的, 我覺得mars上次那招挺不錯的
```
# OPTION SSL
/ OPTION SSL
```
這樣做點手腳, 然後我們developer的readme紀錄一下, 應該就可以找到哪些可以用的功能
