### ISSUE TITLE
排序的上下調整

### ISSUE THREAD

**Issue by ohmkao** [5fpro/rails4-template#29]
參考code
https://github.com/5fpro/election2016-hope/pull/22/files

參考圖
https://trello-attachments.s3.amazonaws.com/55e9619adbb2337d37e74f49/1189x331/49673843be9000dc41315731a8914842/%E6%8E%92%E5%BA%8F.png

**Comment by marsz** [comment]
先做按鈕版的上下

**Comment by marsz** [comment]
移除排序的話
要怎麼排? 放最後?

**Comment by ohmkao** [comment]
設計目的：
 類似 「商品」或是「文章」
不需每個都排序

所以移除排序時，那個值會變成 nil
排序的方式 order("sort ASC, id DESC")

移除時 就會照 id DESC 排

這東西的概念就像是 「重點排序」
其他的就照發佈時間或是ID排

**Comment by phrase5036** [comment]
我覺得排序就四種 
- 向上 + 1
- 向下 - 1
- 置底
- 置頂
四個就好了, 移除排序我實在不知道哪時候會用到  XD
既然都有排序的概念了, 應該是所有東西都要在排序的role裡面

**Comment by marsz** [comment]
@ohmkao  的意思應該是移除排序後（即 sort = nil）就一定會跑到有排序的資料之後（不管是正排或逆排），至於一堆移除排序的資料要如何排，就看 default order 是啥了
@phrase5036 提供的這四種排序我會實做

**Comment by ohmkao** [comment]
@marsz 是的，我到時候在看 commit 怎麼寫就可以
