### ISSUE TITLE
預設的 幾個常用型CRUD for admin/xxx

### ISSUE THREAD

**Issue by ohmkao** [5fpro/rails4-template#30]
article / 文章
category / 分類
tag / 標籤
page / 靜態頁
user / 使用者
cover / 封面
attachment / 附件
menu / 選單

**Comment by marsz** [comment]
有點太客製了啦 XD
我想要做好 user 就好，其他的可以從 user 去 clone
@ohmkao

**Comment by marsz** [comment]
不然就是等其他的做完再看這裡還有沒有需要

**Comment by ohmkao** [comment]
可以擺在比較後面
