### ISSUE TITLE
IP白名單

### ISSUE THREAD

**Issue by ohmkao** [5fpro/rails4-template#31]
後台控制
https://github.com/5fpro/election2016-official/blob/develop/app/controllers/admin/base_controller.rb#L29

管理方式
1. 後台CRUD+DBtable
2. DBtable(only)
3. ip.yml (寫在code裡)

**Comment by marsz** [comment]
補充：讓後台只允許某些 IP 可以存取
IP 管理，比較偏好 `2.` 但是用 redis 存 + 寫 service class

**Comment by phrase5036** [comment]
redis也可以沒有意見 XD, 前提是redis不要放在主機上！

**Comment by ohmkao** [comment]
不要放在EC2上 XD

**Comment by phrase5036** [comment]
先用redis看看好惹, 如果真的有需要改成Table也不會太辛苦啦其實  XD
