### ISSUE TITLE
雙重欄位設計的支援 （預覽＋發佈），前端專用預覽的sha

### ISSUE THREAD

**Issue by ohmkao** [5fpro/rails4-template#32]
例如：

某一些 CMS 系統 的某些 table article 需要比較嚴謹的發佈方式
title, content, pic (前端欄位)
title_pr, content_pr, pic_pr (後端欄位)

後台編輯時，僅能編輯 *_pr 欄位
按下「發佈」時，直執行 欄位資料複製到 前端欄位

好處：
後台可隨意按下 save，前台不會立刻受到影響，還可以 reload 還原
按下「發佈」時才會 push 給前端

壞處：
多了欄位，要多「發佈」動作

**Comment by marsz** [comment]
其實有點看不太懂   是要做「上稿」 + 「權限管理」嗎?
@ohmkao
