### ISSUE TITLE
admin panel permisson management

### ISSUE THREAD

**Issue by marsz** [5fpro/rails4-template#33]
gem `pundit`

**Comment by marsz** [comment]
需要再仔細討論一下要做哪些權限上的範例出來

**Comment by marsz** [comment]
以 user 管理 tag 為範例

**Comment by phrase5036** [comment]
以前我做過的需求是
1. is_super, is_editor, is_xxxx
2. 然後需要綁定不同的action去操作, 舉例來說 editor 可以使用 article#index, article#show, 但是無法存取article#delete
提供參考

**Comment by kzdahlia** [comment]
感覺上光是 user 一個 model 就可以做了：
- super_user
  - 可使用所有操作，包含可刪除其他 user
- 會員管理者
  - user 可新增 user
  - user 可瀏覽其他 user 的資料
  - user 可編輯其他 user 的資料

**Comment by phrase5036** [comment]
可以考慮先用阿丸的架構做就好惹

當然還有更雞巴的權限控管啦
像是某旅行就會有開放讓外部人員使用後台的需求
後來覺得太客制了,  畢竟這只是template
簡單做 歡喜受  XD
