### ISSUE TITLE
config/deploy/production.rb should not start unicorn in shadow server

### ISSUE THREAD

**Issue by marsz** [5fpro/rails4-template#5]
https://ininder.in/1dE1C

**Comment by phrase5036** [comment]
mars, 這邊有測過assets sync嗎
我之前有先拿掉過, 但是我記憶中這樣直接拿掉會有assets sync的問題
我印象中好像是 precompile 跟 sync 是不同台的關係 (produciton部屬),  不知道你有沒有遇到？

**Comment by marsz** [comment]
@phrase5036 
有喔
所以 config 的 `asset_sync.rb` 要 `config.run_on_precompile = false`
然後再寫一支 `asset_sync.rake` 掛到 capistrano 的 callback 裡面去
一來可以自己決定跑 asset sync 的時間點，二來也可以只指定一台跑即可

**Comment by phrase5036** [comment]
@marsz 就是把default關掉再把 precompile 掛掉rake去指定的感覺 XDD

感恩
