### ISSUE TITLE
admin panel _form show image

### ISSUE THREAD

**Issue by marsz** [5fpro/rails4-template#6]
http://ininder.in/1i5f1

**Comment by marsz** [comment]
@kzdahlia  選好檔案後就直接預覽，這有點 JS ，可能這張票先把 style 弄好就好了， JS 的部份之後再說?

**Comment by kzdahlia** [comment]
其實這個 feature 是 @phrase5036 提的喔！

**Comment by phrase5036** [comment]
想問個不太相關的
Factory girl的carriwaver 上傳
有沒有什麼好方法可以在rspec避開

Carriwaver是有提供方法, 只是我覺得還是很慢

**Comment by marsz** [comment]
@phrase5036  在 FactoryGirl 裡面寫不同的 scope
default 沒有上傳圖
有需要的時候再 call
例如 `FactoryGirl.create :user_with_avatar`

**Comment by phrase5036** [comment]
@marsz 這個我們上次好像有口頭討論過了

如果圖片是必填, 你提供了一個解法

model 本身自己都不放valid, 用繼承model去寫valid
然後spec 就可以不用綁在圖片必填上面 XD

感恩
